FROM ubuntu:xenial

ENV TERM=xterm \
    DEBIAN_FRONTEND=noninteractive

RUN rm /bin/sh && \
    ln -s /bin/bash /bin/sh && \
    sed -i "s/mesg n/tty -s \&\& mesg n/" /root/.profile

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y --no-install-recommends locales apt-transport-https && \
    echo 'zh_CN.UTF-8 UTF-8' > /etc/locale.gen && \
    locale-gen && \
    echo -e 'LANG="zh_CN.UTF-8"\nLANGUAGE="zh_CN:zh"\n' > /etc/default/locale && \
    source /etc/default/locale && \
    apt-get install -y --no-install-recommends wget software-properties-common fonts-wqy-microhei && \
    wget -O- -q https://dl.winehq.org/wine-builds/winehq.key | apt-key add -  && \
    add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main' && \
    apt-get update && \
    apt-get install -y --install-recommends wine-staging --allow-unauthenticated && \
    apt-get -y remove wget software-properties-common && \
    apt-get -y autoremove && apt-get clean -y && apt-get autoclean -y && \
    rm -rf var/lib/apt/lists/* var/cache/apt/* var/log/*

ENV LANGUAGE=zh_CN.UTF-8 \
    LC_ALL=zh_CN.UTF-8 \
    LANG=zh_CN.UTF-8 \
    TZ=UTC-8
    
ENTRYPOINT ["wine"]
