name: Build Image

on:
  push:
    branches: [ "docker_build" ]
  pull_request:
    branches: [ "docker_build" ]

jobs:
  build_wine:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./docker-wine/ubuntu
        tags: |
          gfl699468/wine:i386-latest
        push: true
  build_deepin_wine:
    runs-on: ubuntu-latest
    needs: build_wine
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./docker-wine/i386
        tags: |
          gfl699468/deepin-wine:i386-latest
        push: true
  build_wechat:
    runs-on: ubuntu-latest
    needs: build_deepin_wine
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: |
          gfl699468/docker-wechat:latest
        push: true

